### PR TITLE
add switch for the purifier light

### PR DESCRIPTION
**Pull request by kylerw**

### CODE REVIEW

**Comment by robert-alfaro** [comment]
@kylerw does python-iocare work for you? I'm getting an issue with 'code' key not existent in one of the json responses. This doesn't have anything to do with your changes or this component..but since your changes are recent, I'm wondering if something changed in their API recently.. Moreover, it seems like the python-iocare project is closed source (not collaborative).  I mean sure we can look at sources upon installing the package, but seems like it's no longer maintained.

**Review by sarahhenkens — APPROVED** [review]

**Review by sarahhenkens — DISMISSED** [review]

**Comment by sarahhenkens** [comment]
@robert-alfaro, I was originally planning to write my own API client for their API until I found that closed off python project. It was working with my initial prototype. 

We might need to pull an older version during install? Last time I checked, it was working with `0.1.5`.

**Comment by robert-alfaro** [comment]
Something changed in their API recently..I think.  Today I noticed a forced app (Android) update too.

**Comment by deekue** [comment]
this one? https://github.com/evandcoleman/python-iocare

**Comment by robert-alfaro** [comment]
That is the python package used under the hood. It needs updating.

**Comment by skynet01** [comment]
Sooo.. any updates on this? Would love to be able to control the light :)

**Comment by Varjo1** [comment]
> Sooo.. any updates on this? Would love to be able to control the light :)

Seconded!

**Comment by kylerw** [comment]
I don't have write access to the repo to merge or resolve conflicts.

**Comment by RobertD502** [comment]
Would it make more sense to set this up as a light entity instead of a switch entity? Light entities have an on/off component to them like switches.

**Comment by kylerw** [comment]
The light entity is typically used for devices that support dimming and/or color changes. The light on this device does neither so it likely should fall to the switch entity like it has been configured. I am, however, no expert on the design rules so open to feedback.

**Comment by sarahhenkens** [comment]
Looks like we have a merge conflict after merging the other PR :( Can you rebase?

**Comment by RobertD502** [comment]
> The light entity is typically used for devices that support dimming and/or color changes. The light on this device does neither so it likely should fall to the switch entity like it has been configured. I am, however, no expert on the design rules so open to feedback.

I'm not an expert on the design rules either. Based on what you said, I'd agree with sticking to a switch design. There are lights that aren't fully controllable such as the Hue White bulbs, but even then they do still have brightness control, which the light on the purifier doesn't.

**Pull request closed without merging**
