### PR TITLE
Change IOCare to IoCare & update README

### PR DESCRIPTION
**Pull request by RobertD502**
Sorry for another PR Sarah! I just noticed Coway uses the IoCare naming format instead of IOCare, so, I wanted to make sure the integration does the same.

### CODE REVIEW

**Comment by RobertD502** [comment]
@sarahhenkens Sarah, I'm not sure if you saw my comment on a previous PR, but could you possibly send me a collaborator invite for this repo. This way I can help out with reviewing PRs as well as creating releases. Since we haven't used releases for this repo, HACS pushes through any merged PRs as updates. As it stands, users that update through HACS following the last PR merge will have a broken integration since no info is provided to them about breaking changes without the use of a release/accompanying documentation within the release.

**Review by sarahhenkens — APPROVED** [review]

**Comment by sarahhenkens** [comment]
@RobertD502, I've updated the CODEOWNERS to be less restrictive now to only the `readme.md` and the `CODEOWNERS` file itself. This should allow you to merge your own PRs as well and approve others.

Going to work on packaging this up to publish to PyPi as well!

**Comment by RobertD502** [comment]
@sarahhenkens doesn't this give permission to anyone to merge PR requests? Seems like things could get messy. Also, this method doesn't give me release creation permissions. 

I noticed the release you just created is listed as 0.0.1- are we not following the version naming scheme as seen in the manifest (2021.4.0)?

**Comment by sarahhenkens** [comment]
I was thinking that we can start using semver instead of a date-based versioning 🤔  PRs should still be approved before merging once they have approval. Afaik, since you and I are the only collaborators on this repo, we only have the ability to approve.

**Comment by RobertD502** [comment]
@sarahhenkens I don't believe I have been added as a collaborator. I didn't get an e-mail invitation and don't have any of the permissions that come with being added as a collaborator.

I don't have any strong feelings towards one or the other so semver is fine with me. I'll need to change the README and manifest to reflect your release of 0.0.1. Also, need to edit the release to document the breaking changes, which is why I was looking to be added as a collaborator (aside from being able to merge PRs).

**Comment by RobertD502** [comment]
Just to confirm my suspicion...I created a new PR with the manifest changes and don't have the ability to approve- something a collaborator would be able to do. I also noticed that the PR now doesn't list anyone as a reviewer. I'm assuming this is because the codeowner file changes only add you as a reviewer when the README or codeowner file is part of the PR? With no collaborators no reviewer is added to PRs involving other files?

[Adding Collaborators](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository)

**Comment by sarahhenkens** [comment]
I kept the codeowners to the manifest and readme file. I'm also happy to transfer this entire repository to your account! I don't have much time anymore to maintain this plugin :(

**Comment by RobertD502** [comment]
@sarahhenkens I don't foresee myself having as much time as it would take to maintain the repository myself. However, by adding me as a collaborator, it will allow both of us to review and merge changes / create releases so that one person isn't relied on by the rest of the users that use the integration. I appreciate the offer though! Let me know about adding me as a collaborator to this repository.

**Pull request merged**
